/**
 * PDF Report Generator using pdfkit
 */

import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { config } from '../../../config/index.js';
import type { ProjectDocument, ProjectData } from '../../../db/mongodb.js';
import { WithId } from 'mongodb';

export async function generatePDF(
  project: WithId<ProjectDocument>,
  projectData: ProjectData | Record<string, unknown>,
  reportType: string
): Promise<string> {
  // Ensure upload directory exists
  const uploadDir = config.UPLOAD_DIR;
  if (!fs.existsSync(uploadDir)) {
    fs.mkdirSync(uploadDir, { recursive: true });
  }

  const filename = `report_${project._id.toString()}_${Date.now()}.pdf`;
  const filepath = path.join(uploadDir, filename);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(filepath);

    doc.pipe(stream);

    // Header
    doc.fontSize(24).text('VitruviAI', { align: 'center' });
    doc.fontSize(18).text('Construction Analysis Report', { align: 'center' });
    doc.moveDown();

    // Project Info
    doc.fontSize(16).text('Project Information', { underline: true });
    doc.fontSize(12);
    doc.text(`Name: ${project.name}`);
    doc.text(`Location: ${project.location || 'N/A'}`);
    doc.text(`Status: ${project.status || 'Active'}`);
    doc.text(`Mode: ${project.mode}`);
    doc.text(`Report Type: ${reportType}`);
    doc.text(`Generated: ${new Date().toLocaleString()}`);
    doc.moveDown();

    // Progress Section
    if (projectData && typeof projectData === 'object') {
      const data = projectData as ProjectData;

      doc.fontSize(16).text('Progress Overview', { underline: true });
      doc.fontSize(12);
      doc.text(`Stage: ${data.stage || 'Unknown'}`);
      doc.text(`Progress: ${data.progressPercentage || 0}%`);
      doc.text(`Time Remaining: ${data.timeRemaining || 'Unknown'}`);
      doc.text(`Delays Flagged: ${data.delaysFlagged || 0}`);
      doc.moveDown();

      // Financials
      if (data.financials) {
        doc.fontSize(16).text('Financial Summary', { underline: true });
        doc.fontSize(12);
        const fin = data.financials as Record<string, unknown>;
        doc.text(`Budget Total: $${(fin.budgetTotal as number || 0).toLocaleString()}`);
        doc.text(`Budget Spent: $${(fin.budgetSpent as number || 0).toLocaleString()}`);
        doc.text(`Budget Remaining: $${(fin.budgetRemaining as number || 0).toLocaleString()}`);
        doc.text(`Cost Overrun: ${fin.costOverrun || 0}%`);
        doc.moveDown();
      }

      // Manpower
      if (data.manpower) {
        doc.fontSize(16).text('Manpower', { underline: true });
        doc.fontSize(12);
        const mp = data.manpower as Record<string, unknown>;
        doc.text(`Total Workers: ${mp.total || 0}`);
        doc.text(`Skilled: ${mp.skilled || 0}`);
        doc.text(`Unskilled: ${mp.unskilled || 0}`);
        doc.text(`Safety Score: ${mp.safetyScore || 0}%`);
        doc.text(`Productivity Index: ${mp.productivityIndex || 0}%`);
        doc.moveDown();
      }

      // Compliance
      if (data.compliance) {
        doc.fontSize(16).text('Compliance', { underline: true });
        doc.fontSize(12);
        const comp = data.compliance as Record<string, unknown>;
        doc.text(`Structural Score: ${comp.structuralScore || 0}%`);
        doc.text(`Sustainability Rating: ${comp.sustainabilityRating || 'N/A'}`);
        doc.text(`Code Violations: ${comp.codeViolations || 0}`);
        doc.moveDown();
      }

      // Insights
      if (data.insights && Array.isArray(data.insights)) {
        doc.fontSize(16).text('AI Insights', { underline: true });
        doc.fontSize(12);
        data.insights.forEach((insight, index) => {
          doc.text(`${index + 1}. ${insight}`);
        });
      }
    }

    // Footer
    doc.moveDown(2);
    doc.fontSize(10).text('Generated by VitruviAI - AI-Powered Construction Intelligence', {
      align: 'center',
      color: 'gray',
    });

    doc.end();

    stream.on('finish', () => {
      resolve(`/uploads/${filename}`);
    });

    stream.on('error', reject);
  });
}
